# Generated by Django 4.0.1 on 2022-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllitsonModel',
            fields=[
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'admin_register',
            },
        ),
    ]
